// Placeholder firebase_options.dart
// Replace this file with the one generated by the FlutterFire CLI
// (flutterfire configure) which provides platform-specific FirebaseOptions.

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  // Return null to indicate no generated options are available. The
  // CloudSyncService.init() handles this by falling back to plain
  // Firebase.initializeApp().
  static FirebaseOptions? get currentPlatform => null;
}
