// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiXFs4LoopMzlqnRtxgM7cR9-fkxmov3g',
    appId: '1:991530506096:web:ad5cb3da3080c4a42a21b5',
    messagingSenderId: '991530506096',
    projectId: 'smartnest-f9b99',
    authDomain: 'smartnest-f9b99.firebaseapp.com',
    storageBucket: 'smartnest-f9b99.firebasestorage.app',
    measurementId: 'G-9SP28BPVDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiFd5zg7O4NM1_7-whp82AeQHpjslrF58',
    appId: '1:991530506096:android:baec25325c1fb27f2a21b5',
    messagingSenderId: '991530506096',
    projectId: 'smartnest-f9b99',
    storageBucket: 'smartnest-f9b99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-G2kYuPPhr5X5Eg-6-SVkggEX0qbsSkY',
    appId: '1:991530506096:ios:8119e586e8a10a962a21b5',
    messagingSenderId: '991530506096',
    projectId: 'smartnest-f9b99',
    storageBucket: 'smartnest-f9b99.firebasestorage.app',
    iosBundleId: 'com.example.smartNestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-G2kYuPPhr5X5Eg-6-SVkggEX0qbsSkY',
    appId: '1:991530506096:ios:8119e586e8a10a962a21b5',
    messagingSenderId: '991530506096',
    projectId: 'smartnest-f9b99',
    storageBucket: 'smartnest-f9b99.firebasestorage.app',
    iosBundleId: 'com.example.smartNestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiXFs4LoopMzlqnRtxgM7cR9-fkxmov3g',
    appId: '1:991530506096:web:8cd0546ef428090a2a21b5',
    messagingSenderId: '991530506096',
    projectId: 'smartnest-f9b99',
    authDomain: 'smartnest-f9b99.firebaseapp.com',
    storageBucket: 'smartnest-f9b99.firebasestorage.app',
    measurementId: 'G-85DYKM00SC',
  );
}
