import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
// Provider package removed; provide simple InheritedWidget locally instead.
import 'package:smart_nest_app/screens/splash_screen.dart';
import 'package:smart_nest_app/config/app_theme.dart';
import 'package:smart_nest_app/services/auth_service.dart';
import 'package:smart_nest_app/services/firestore_service.dart';
// Generated by `flutterfire configure`. Throws a readable error if that has
// not been run yet, rather than failing deep inside the native SDK.
import 'package:smart_nest_app/firebase_options.dart' show DefaultFirebaseOptions;
import 'package:smart_nest_app/services/app_bootstrap.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    // Offline persistence and push notifications. Kept out of this file so the
    // backend layer owns its own setup -- see lib/services/app_bootstrap.dart.
    await initBackendServices();
  } catch (e) {
    // Without Firebase the app still starts, and the screens fall back to
    // their demo behaviour. Worth keeping: it means a missing google-services
    // file shows up as a log line, not a white screen on launch.
    debugPrint('Firebase init failed, running in demo mode: $e');
  }

  runApp(ServicesProvider(
    authService: AuthService(),
    firestoreService: FirestoreService(),
    child: const SmartNestApp(),
  ));
}

class ServicesProvider extends InheritedWidget {
  final AuthService authService;
  final FirestoreService firestoreService;

  const ServicesProvider({
    required this.authService,
    required this.firestoreService,
    required super.child,
    super.key,
  });

  static ServicesProvider of(BuildContext context) {
    final ServicesProvider? result = context.dependOnInheritedWidgetOfExactType<ServicesProvider>();
    assert(result != null, 'No ServicesProvider found in context');
    return result!;
  }

  @override
  bool updateShouldNotify(ServicesProvider oldWidget) =>
      authService != oldWidget.authService || firestoreService != oldWidget.firestoreService;
}

class SmartNestApp extends StatelessWidget {
  const SmartNestApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Nest',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      home: const SplashScreen(),
    );
  }
}
